// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {tokenizer} from "./tokenizer"
import {highlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "+pQVQTOOOtQPO'#CcO!SQPO'#D`O!yQTO'#CbOOQS'#Dd'#DdO#QQPO'#DcO#fQUO'#DcOOQO'#Da'#DaO$VQTO'#DgOOQO'#Cw'#CwO$^QTO'#DkOOQO'#DR'#DROOQO'#D`'#D`O$fQPO'#D_OOQS'#D_'#D_OOQS'#DV'#DVQVQTOOO$VQTO,58}O$VQTO,58}O%YQPO'#CcO%jQPO,58|O%vQPO,58|O&sQPO,58|O&zQUO'#DcOOQS'#Dc'#DcOOQS'#Ca'#CaO$VQTO'#CtOOQS'#Db'#DbOOQS'#DW'#DWO'hQUO,58zO'{QTO,59pO(YQPO,5:RO(aQPO,5:ROOQS'#DZ'#DZO(fQTO'#DTO(nQPO,5:VOOQS,59y,59yOOQS-E7T-E7TOOQO1G.i1G.iO(sQPO1G.iO$VQTO,59SO$VQTO,59SOOQS1G.h1G.hOOQS,59`,59`OOQS-E7U-E7UOOQO1G/[1G/[O)[QTO1G/mOOQS-E7X-E7XO)lQTO1G/qOOQO1G.n1G.nO)|QPO1G.nOOQO'#Cz'#CzOOQO7+%X7+%XO*WQTO7+%YOOQO7+%]7+%]O*nQTO7+%^O+OQPO'#DXO+TQTO'#DjOOQO'#C{'#C{O+kQPO<<HtO+vQPO<<HxOOQS,59s,59sOOQS-E7V-E7VO$VQTO'#C|OOQO'#DY'#DYO+{QPOAN>`O,WQPO'#DOOOQOAN>`AN>`O,RQPOAN>`OOQOAN>dAN>dO,]QPO,59hO,dQPO,59hOOQO-E7W-E7WOOQOG23zG23zO,iQPOG23zO,nQPO,59jO,sQPO1G/SOOQOLD)fLD)fO*nQTO1G/UO*WQTO7+$nOOQO7+$p7+$pOOQO<<HY<<HY",
  stateData: ",{~O!QOS~OPUOQSOeSOfSOgSOlWOvYO!XRO!]^O~OWaOXaOYbOZbO~OWaOXaOYbOZbO!]!SX!a!SX~OQSOeSOfSOgSO!XRO~OPgO~P!hOW!VXX!VXY!VXZ!VX!]!SX!a!SX~OPhO]nOijOW!VXX!VXY!VXZ!VX!]jX!ajX~P!hOPhO~P!hOPqOmwP~O!]tO!atO~O]xO^xO_xO`xOaxObxOcyOdyO~OWaOXaOYbOZbO~P$nOWaOXaOYbOZbO!YzO~OW!VXX!VXY!VXZ!VX]!VX^!VX_!VX`!VXa!VXb!VXc!VXd!VX~O!YzO~P%{OPhOQSOeSOfSOgSOijO!XRO!YjX~P%{OPhOijO!]Sa!aSa!YSa~P!hOPUOlWOvYO~P!hOm!OO~P$nOm!OO~OPqOmwX~Om!QO~OWaOXaOYViZVi!]Vi!aVi!YVi~OPUOlWOvYO!]!VO~P!hOPUOlWOvYO!]!XO~P!hO!Y[im[i~P$nOPUOlWOvYOq!^Ps!^Pt!^P~P!hOPUOlWOvYOt!^P~P!hO!]!_O~OPUOlWOvYOq!^Xs!^Xt!^X~P!hOq!aOs!dOt!eO~Ot!gO~Oq!aOs!dOt!kO~Om!mO~Om!nO~P$nOm!nO~Ot!oO~O!]!pO~O!]!qO~OfZ~",
  goto: "(o!aPPPP!b!o!t#]PPPP#rPPPPPPPPPPP!oP!b$OPP$[$_$hP$lPP$OP$r$O$u${%S%]%cPPP%i%m&R&b&g'bPP'}'}P(Z(c(cgVOR`n!O!Q!V!X!Z!p!qVkUgm{SORUW`abgjmnxy!O!Q!V!X!Z!a!p!qdQO`n!O!Q!V!X!Z!p!qQdRQvaRwbQeRQpWQ!RyR!i!ae[O`n!O!Q!V!X!Z!p!qR!U!OQ!]!VQ!r!pR!s!qT!b!]!cQ!f!]R!l!cRsYQ`ORu`SmUgR|mW!Z!V!X!p!qR!`!ZQ!c!]R!j!cQrYR!PrT_O`S]O`Q}nQ!T!OQ!W!QZ!Y!V!X!Z!p!qd[O`n!O!Q!V!X!Z!p!qReRVlUgmdPO`n!O!Q!V!X!Z!p!qQcRUiUgmQoWQvaQwbQ{jQ!RxQ!SyR!h!adTO`n!O!Q!V!X!Z!p!qQfRehUWabgjmxy!aeXO`n!O!Q!V!X!Z!p!qU![!V!p!qR!^!XeZO`n!O!Q!V!X!Z!p!q",
  nodeNames: "⚠ Identifier Word Program FunctionCall PositionalArg ParenExpr BinOp operator operator operator operator ConditionalOp operator operator operator operator operator operator operator operator String Number Boolean NamedArg NamedArgPrefix FunctionCallOrIdentifier IfExpr keyword colon ThenBlock ThenBlock ElsifExpr keyword ElseExpr keyword end FunctionDef keyword Params Assign",
  maxTerm: 63,
  nodeProps: [
    ["closedBy", 29,"end"],
    ["openedBy", 36,"colon"]
  ],
  propSources: [highlighting],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "-m~RmXY!|YZ#Rpq!|qr#Wwx#cxy$Qyz$Vz{$[{|$a}!O$f!P!Q%X!Q![$n![!]%^!]!^#R!^!_%c!_!`%p!`!a%u#T#U&S#U#X&h#X#Y']#Y#Z)y#Z#]&h#]#^+r#^#c&h#c#d,^#d#h&h#h#i,x#i#o&h~~-h~#RO!Q~~#WO!]~~#ZP!_!`#^~#cO^~~#fTOw#cwx#ux;'S#c;'S;=`#z<%lO#c~#zOe~~#}P;=`<%l#c~$VO!X~~$[O!Y~~$aOW~~$fOY~~$kPZ~!Q![$n~$sQf~!O!P$y!Q![$n~$|P!Q![%P~%UPf~!Q![%P~%^OX~~%cOm~~%hP_~!_!`%k~%pO`~~%uO]~~%zPa~!_!`%}~&SOb~~&VS!_!`&c#T#b&h#b#c&q#c#o&hQ&hOiQQ&kQ!_!`&c#T#o&h~&tS!_!`&c#T#W&h#W#X'Q#X#o&h~'VQc~!_!`&c#T#o&hR'`U!_!`&c#T#`&h#`#a'r#a#b&h#b#c)_#c#o&hR'uS!_!`&c#T#g&h#g#h(R#h#o&hR(UU!_!`&c#T#X&h#X#Y(h#Y#]&h#]#^(s#^#o&hR(mQsP!_!`&c#T#o&hR(vS!_!`&c#T#Y&h#Y#Z)S#Z#o&hR)XQqP!_!`&c#T#o&hR)bS!_!`&c#T#W&h#W#X)n#X#o&hR)sQtP!_!`&c#T#o&h~)|T!_!`&c#T#U*]#U#b&h#b#c+g#c#o&h~*`S!_!`&c#T#`&h#`#a*l#a#o&h~*oS!_!`&c#T#g&h#g#h*{#h#o&h~+OS!_!`&c#T#X&h#X#Y+[#Y#o&h~+aQg~!_!`&c#T#o&hR+lQvP!_!`&c#T#o&hR+uS!_!`&c#T#Y&h#Y#Z,R#Z#o&hR,WQlP!_!`&c#T#o&h~,aS!_!`&c#T#f&h#f#g,m#g#o&h~,rQd~!_!`&c#T#o&h~,{S!_!`&c#T#f&h#f#g-X#g#o&h~-[S!_!`&c#T#i&h#i#j*{#j#o&h~-mO!a~",
  tokenizers: [0, 1, tokenizer],
  topRules: {"Program":[0,3]},
  tokenPrec: 546
})
