// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Identifier = 1,
  Word = 2,
  Program = 3,
  Expression = 4,
  FunctionCall = 5,
  PositionalArg = 6,
  ParenExpr = 7,
  String = 8,
  Number = 9,
  Boolean = 10,
  NamedArg = 11,
  IncompleteNamedArg = 12,
  FunctionCallOrIdentifier = 13,
  BinOp = 14
