// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Assignment = 2,
  Identifier = 3,
  equals = 4,
  Function = 5,
  fn = 6,
  Params = 7,
  BinOp = 9,
  Number = 14,
  String = 15,
  Boolean = 16,
  leftParen = 17,
  rightParen = 18
